### ISSUE TITLE
Upgrading `duckdb-rs` to 1.2.0 fails linking on Ubuntu 22.04

### ISSUE THREAD

**Issue by cpaika** [duckdb/duckdb-rs#436]
When trying to upgrade duckdb-rs from 1.1.1 to 1.2.0, we're getting compilation failures on our Linux build machines when using the `bundled` flag.  It looks like duckdb compiles successfully, but linking fails into the final binary.  This build is working with duckdb 1.1.1, a change in 1.2.0 is somehow breaking it.

```
 > [8/8] RUN $HOME/.cargo/bin/cargo test:
266.3   = note: /usr/bin/ld: /app/target/debug/deps/liblibduckdb_sys-f5c8fd0dd29e7ad5.rlib(d72e143842620a4d-ub_src_planner_expression.o): in function `void duckdb::DynamicCastCheck<duckdb::ListLambdaBindData, duckdb::FunctionData>(duckdb::FunctionData const*)':
266.3           /app/target/debug/build/libduckdb-sys-51da510693e3ab30/out/duckdb/src/include/duckdb/common/helper.hpp:262: undefined reference to `typeinfo for duckdb::ListLambdaBindData'
266.3           /usr/bin/ld: /app/target/debug/build/libduckdb-sys-51da510693e3ab30/out/duckdb/src/include/duckdb/common/helper.hpp:262: undefined reference to `typeinfo for duckdb::ListLambdaBindData'
266.3           collect2: error: ld returned 1 exit status
266.3
266.3   = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
266.3   = note: use the `-l` flag to specify native libraries to link
266.3   = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)
266.3
266.4 error: could not compile `duckdb-repro` (bin "duckdb-repro" test) due to 1 previous error
Dockerfile:23
```

I've included a minimal reproduction of the issue here: https://github.com/cpaika/duckdb-reproduction/tree/main

My guess is this is related to RTTI, or the LambdaBindGen object isn't being included in the final artifact somehow but not sure.

Any ideas what the problem?  Or if there's a compilation flag to fix it?

**Comment by jessekrubin** [comment]
ditto! same thing here!

**Comment by Maxxen** [comment]
This looks like the same issue that ultimately made us disable the ASAN CI job. Im also not sure why this started with the 1.2.0 upgrade, this part of the code, the "lambda bind info" has not been touched in years. Im going to try to investigate, but I probably wont have time in the coming week or two.

Note that we do link successfully as part of the normal linux CI job here on github.

**Comment by fxwiegand** [comment]
We are also experiencing the same issue in the condo build of one of our tools that uses duckdb-rs: https://github.com/bioconda/bioconda-recipes/actions/runs/13331085053/job/37235267578?pr=53877

**Comment by Maxxen** [comment]
Ok:
- good news: I think I've figured out a fix
- bad news: it's going to require a patch in core DuckDB
- good news: there's a duckdb bug fix release scheduled in early march. 

Still, ill talk to the rest of the team on Monday to see if there's any way to resolve this earlier, it might be possible to bundle and apply some patches during the rust build step, but not sure how much work that will be.

**Comment by jessekrubin** [comment]
@Maxxen thanks duder!

**Comment by wyhaya** [comment]
DuckDB has released version v1.2.1. Can this issue be fixed?

**Comment by Maxxen** [comment]
v1.2.1 is now released and should have fixed this. Please let me know if you run into any more issues.
