### PR TITLE
Enable pre-release testing

### PR DESCRIPTION
**Pull request by mlafeldt**
Add `--sha` override to pin the bundled DuckDB sources to a specific commit, with or without a version bump:

    ./upgrade.sh v1.5.4 --sha 08e34c447b    # planned release, source pinned to commit
    ./upgrade.sh --sha 08e34c447b           # test a commit, no version bump

refs https://github.com/duckdblabs/duckdb-internal/issues/7516

### CODE REVIEW

**Comment by mlafeldt** [comment]
CI failure `error C2653: 'stdext': is not a class or namespace name` is caused by #786, which will be fixed upstream. Ignoring.
